---
- name: Deploy GitHub Packages to IBM-Ace 
  hosts: all 
  become: true
  gather_facts: true
  tasks:
    - name: Move File foo to destination bar
      become: yes
      become_user: ec2-user
      shell: |
        pwd 
        ls
        mv *.bar /home/ec2-user/actions-runner/_work/barpoc/barpoc/SampleApiproject.generated.bar
    - name: Deploy Bar file 
      become: yes
      become_user: ec2-user
      shell: |
             sh /home/ec2-user/Software/ace-12.0.12.0/server/mqsi.sh
