---
- name: Deploy GitHub Packages to IBM-Ace 
  hosts: all 
  become: true
  gather_facts: true
  tasks:
    - name: Move File foo to destination bar
      shell: |
        pwd 
        ls
        mv *.bar /home/ec2-user/actions-runner/_work/barpoc/barpoc/SampleApiproject.generated.bar
    - name: deploy Bar file 
      shell: |
             export MQSI_WORKPATH=/home/ec2-user/Software/ace-12.0.12.0/server
             export PATH=$MQSI_WORKPATH/bin:$PATH
             . ./home/ec2-user/Software/ace-12.0.12.0/server/bin/mqsiprofile
             mqsireadbar -b /home/ec2-user/actions-runner/_work/barpoc/barpoc/SampleApiproject.generated.bar  > /home/ec2-user/actions-runner/_work/barpoc/barpoc/SampleApiproject.generated.properties -r 
             mqsiapplybaroverride -b /home/ec2-user/actions-runner/_work/barpoc/barpoc/SampleApiproject.generated.bar > /home/ec2-user/actions-runner/_work/barpoc/barpoc/SampleApiproject.generated.properties -r
             mqsideploy MyBroker --integration-server MyExecutionGroup --bar-file /home/ec2-user/actions-runner/_work/barpoc/barpoc/SampleApiproject.generated.bar
