---
- name: Deploy GitHub Packages to IBM-Ace 
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Move File foo to destination bar
      shell: |
        pwd 
        ls
        mv *.bar SampleApiproject.generated.bar
    - name: Deploy Bar file 
      shell: |
             cd /home/ec2-user/Software/ace-12.0.12.0/server/bin
             . ./mqsiprofile
             . ./mqsiapplybaroverride -b SampleApiproject.generated.bar -p SampleApiproject.generated.properties -r
             . ./mqsideploy MyNode --integration-server MyExecutionGroup --bar-file SampleApiproject.generated.bar       
