---
- name: Deploy GitHub Packages to IBM-Ace 
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Move File foo to destination bar
      shell: |
        pwd 
        ls
        mv *.bar SampleApiproject.generated.bar
    - name: Deploy Bar file 
      shell: |
             . ./home/ec2-user/Software/ace-12.0.12.0/server/bin/mqsiprofile
             . ./home/ec2-user/Software/ace-12.0.12.0/server/bin/mqsiapplybaroverride -b /home/ec2-user/actions-runner/_work/barpoc/barpoc/SampleApiproject.generated.bar -p /home/ec2-user/actions-runner/_work/barpoc/barpoc/SampleApiproject.generated.properties -r
             . ./home/ec2-user/Software/ace-12.0.12.0/server/bin/mqsideploy MyNode --integration-server MyExecutionGroup --bar-file /home/ec2-user/actions-runner/_work/barpoc/barpoc/SampleApiproject.generated.bar       
