---
- name: Deploy GitHub Packages to IBM-Ace 
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Move File foo to destination bar
      shell: |
        pwd 
        ls
        mv *.bar SampleApiproject.generated.bar
    - name: start the mqsi profile 
      shell: |
             cd /home/ec2-user/Software/ace-12.0.12.0/server/bin
             . ./mqsiprofile
    - name: Read Bar file 
      shell: |
             . ./mqsireadbar -b /home/ec2-user/actions-runner/_work/barpoc/barpoc/SampleApiproject.generated.bar  > /home/ec2-user/actions-runner/_work/barpoc/barpoc/SampleApiproject.generated.properties -r 
    - name: override Bar file 
      shell: |
             . ./mqsiapplybaroverride -b /home/ec2-user/actions-runner/_work/barpoc/barpoc/SampleApiproject.generated.bar -p /home/ec2-user/actions-runner/_work/barpoc/barpoc/SampleApiproject.generated.properties -r
    - name: Deploy Bar file 
      shell: |
             . ./mqsideploy MyNode --integration-server MyExecutionGroup --bar-file /home/ec2-user/actions-runner/_work/barpoc/barpoc/SampleApiproject.generated.bar       
