---
- name: Deploy GitHub Packages to IBM-Ace 
  hosts: all 
  become: true
  gather_facts: true
  tasks:
    - name: Move File foo to destination bar
      become: yes
      become_user: ec2-user
      shell: |
        pwd 
        ls
        mv *.bar /home/ec2-user/actions-runner/_work/barpoc/barpoc/SampleApiproject.generated.bar
    - name: set path
      shell: |
             export MQSI_WORKPATH=/home/ec2-user/Software/ace-12.0.12.0/server
             export PATH=$MQSI_WORKPATH/bin:$PATH
             cd /home/ec2-user/Software/ace-12.0.12.0/server/bin/
             . ./mqsiprofile
    - name: Read Bar file 
      shell: |
             cd /home/ec2-user/Software/ace-12.0.12.0/server/bin/
             mqsireadbar -b /home/ec2-user/actions-runner/_work/barpoc/barpoc/SampleApiproject.generated.bar  > /home/ec2-user/actions-runner/_work/barpoc/barpoc/SampleApiproject.generated.properties -r 
    
